### PR TITLE
RA-1641:Condition list--inactive conditions are not displayed

### PR DESCRIPTION
**Pull request by gitcliff**
LINK:https://issues.openmrs.org/browse/RA-1641
Condition list--inactive conditions are not displayed

### CODE REVIEW

**Comment by mozzy11** [comment]
Looks good

**Comment by mozzy11** [comment]
@dkayiwa , i tested this and it works fine

**Comment by mogoodrich** [comment]
Are we sure that the condition history is always sorted properly from earliest to latest? What happens if I add a condition and then mark it inactive on the same day?

**Comment by mozzy11** [comment]
@mogoodrich  sure its sorted poperly from earliest to latest. I did several testing regarding that. Actually all the testing i did , i was adding several conditions , activating , and de-activating them on the same day. The condition History is properly sorted. The order in which the condition history is persisted in the database , is the same order in which it is retrieved.

**Comment by mogoodrich** [comment]
Thanks @mozzy11 I will do some testing!

**Pull request merged**
