### PR TITLE
RA-1843

### PR DESCRIPTION
**Pull request by mogoodrich**
https://issues.openmrs.org/browse/RA-1843

### CODE REVIEW

**Review by cioan — COMMENTED** [review]
Looks good! Thanks @mogoodrich !

**Review by cioan — APPROVED** [review]
LGTM!

**Review by dkayiwa — APPROVED** [review]

**Review by mseaton — APPROVED** [review]
LGTM

**Comment by mogoodrich** [comment]
Thanks everyone, merging!

**Pull request merged**
