### PR TITLE
RA-1899: Fix broken tests

### PR DESCRIPTION
**Pull request by brandones**
This addresses three problems identified in [RA-1899](https://issues.openmrs.org/browse/RA-1899):

- When Maven would run the tests, test failures would not cause the build to fail. This was fixed by upgrading the maven plugin.
- The tests are broken. This was fixed by reverting https://github.com/openmrs/openmrs-module-coreapps/pull/387 . More info on the reasoning for that is in [a comment there](https://github.com/openmrs/openmrs-module-coreapps/pull/387#issuecomment-828613239).
- There was a minor error in another test, unrelated to the above. The mock data was fixed.

The reverted commit was attempting to fix https://issues.openmrs.org/browse/RA-1864 and https://issues.openmrs.org/browse/RA-1871 . Those tickets will need re-testing.

### CODE REVIEW

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
Of course, I can see from the Travis log that we have yet another broken test, but it looks like that one has been broken for a while.

**Comment by brandones** [comment]
Thanks for the review! Where do you see the Travis log, @ibacher ? GitHub doesn't show any checks.

**Comment by ibacher** [comment]
It's [here](https://travis-ci.org/github/openmrs/openmrs-module-coreapps/builds/768722157#L238). The Travis checks are hidden under the "View Details" button on the merge commit. It's also a Java-based test, so nothing to do with this PR.

**Comment by brandones** [comment]
Nice, thanks Ian.

**Comment by mogoodrich** [comment]
There were a couple that had been broken for a while that we had missed because Maven was always "passing"... but I *thought* I fixed those...

**Comment by mogoodrich** [comment]
Oh, never mind, I see you were talking about unrelated Java tests.

**Comment by ibacher** [comment]
Yep, apparently this module was full of failing tests that don't actually fail the build 😁

**Comment by mogoodrich** [comment]
Actually, I took a look at that test and it was passing, it was just tangentially throwing a NPE while rendering a success message... :)  I think I fixed it here:

https://github.com/openmrs/openmrs-module-coreapps/commit/dc0ee14d420d706100219102cd0f767819081279

**Comment by ibacher** [comment]
Lol... that figures. Thanks @mogoodrich!

**Pull request merged**
