### PR TITLE
RA-1459: Display end date in inactive condition tab

### PR DESCRIPTION
**Pull request by haripriya999**
# RA-1459: Added End Date column in Inactive Conditions tab

## Description of what I changed
 1) Added code to manageConditions.gsp and ManageConditionsController to add End date column and functionality to inactive conditions tab
2) Corrected label of Onset Date

## Issue I worked on

see https://issues.openmrs.org/browse/RA-1459

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
I would love @haripriya999 to attach, on the JIRA ticket, screenshots with the effects of these changes. That way, i would be sure that she tested the user interface and confirmed that all is well. 😊

**Comment by haripriya999** [comment]
I attached the screenshots on JIRA ticket :)

**Comment by dkayiwa** [comment]
@haripriya999 the pull request does not address all that is mentioned in the ticket description.

**Comment by haripriya999** [comment]
changed have been updated

**Comment by dkayiwa** [comment]
On the JIRA ticket, can you attach screenshots with the effects of your changes?

**Comment by haripriya999** [comment]
Added screenshots to JIRA

**Pull request merged**
