### PR TITLE
Add extension points in PatientHeader

### PR DESCRIPTION
**Pull request by rbuisson**
Add firstLineFragments and secondLineFragents extensions
	modified:   omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/PatientHeaderFragmentController.java
	modified:   omod/src/main/webapp/fragments/patientHeader.gsp

Replace the current active visit status bar with a standalone controller
	new file:   omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientheader/ActiveVisitStatusFragmentController.java
	new file:   omod/src/main/webapp/fragments/patientheader/activeVisitStatus.gsp
	new file:   omod/src/main/resources/apps/patientHeader_extension.json

Change distro dependency version
	modified:   pom.xml

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rbuisson this has merge conflicts. Did u start by pulling the latest changes?

**Comment by rbuisson** [comment]
Oups. I didn't pull upstream.
I am doing it now. Should I merge with upstream/master ?

**Comment by dkayiwa** [comment]
As long as the pull request shows only the changes you made, minus the merge. :)

**Comment by rbuisson** [comment]
@dkayiwa The conflicts are not related to the changes I've made. I guess they are due to the version of patientHeader.gsp I use which is from Coreapps 1.6, quite far from the master.

How to do ?

**Comment by dkayiwa** [comment]
@rbuisson you can do a fresh checkout of the module in a separate folder, add in your changes, then create a pull request

**Comment by dkayiwa** [comment]
@rbuisson can you remove the merge from the pull request? :)

**Comment by rbuisson** [comment]
Well, not sure actually. If I remove the merge, then I guess the conflicts will appear again isn't it ?

**Comment by dkayiwa** [comment]
@rbuisson the easiest thing to do is pull the latest module in a separate folder, add in the changes to do with adding extension points to the patient header, then create a clean pull request. :)

**Comment by rbuisson** [comment]
Only that.
It means adding an extension point and export the current visit status bar to a standalone fragement.
It is not a big change, but involves changes in few files. See the commit message.

OK, I'll recreate it from scratch, in a new folder.

**Comment by rbuisson** [comment]
I'll close the pull request and do a new one when I have more time.
Thanks for your time @dkayiwa

**Pull request closed without merging**
