### PR TITLE
Have added the new  List of encounters types in recognition for form filling orders

### PR DESCRIPTION
**Pull request by sherrif10**
Encounter types for form filling orders
https://issues.openmrs.org/projects/RA/issues/RA-1620?filter=allopenissues

### CODE REVIEW

**Comment by sherrif10** [comment]
@dkayiwa kindly review this PR  thanks
https://github.com/sherrif10/openmrs-module-coreapps/commit/06bab73a142bd3a2f954b3573c42aecfbf656811

**Comment by dkayiwa** [comment]
@arinze in working on this.

**Comment by sherrif10** [comment]
@Arinze reported the issue and its status was waiting for dev. Does that
mean i unassign from that work.

**Comment by sherrif10** [comment]
@arinze feel free to ping me to help you if at all possible

**Pull request closed without merging**
