### PR TITLE
UHM-4634 Reformat patient header for better viewing on tablets

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/UHM-4634

Screenshot from 2020-06-24 15-49-23
Screenshot from 2020-06-24 16-04-08
Screenshot from 2020-06-24 16-04-23
Screenshot from 2020-06-24 16-04-37
Screenshot from 2020-06-24 16-04-59
Screenshot from 2020-06-24 16-05-28

### CODE REVIEW

**Comment by ssmusoke** [comment]
@brandones excellent, just a question for you, does it make sense to make the header HTML Bootstrap compliant to ease the responsiveness, since that is available as a layout?

**Comment by brandones** [comment]
Thanks @ssmusoke ! Yes, I used Bootstrap to make this responsive.

**Comment by brandones** [comment]
Reflecting @mogoodrich's feedback,

Screenshot from 2020-06-30 10-33-02

**Comment by brandones** [comment]
Note that the box for "Show Contact Info" isn't something I made. It's old CSS that uncovered when I deleted some of the newer CSS. It's like geologic layers of CSS detritus. The advantage of the box is that it looks less like a link, which I expect to take me somewhere. The advantage of the current RefApp styling is that it looks less cluttered. I'm fine with either.

The style in the RefApp demo, for reference:
Screenshot from 2020-06-30 11-00-28

**Comment by brandones** [comment]
I played around a bit more with where things could go. Here's an idea:

Screenshot from 2020-06-30 10-49-48
Screenshot from 2020-06-30 11-00-41

**Comment by ssmusoke** [comment]
> Thanks @ssmusoke ! Yes, I used Bootstrap to make this responsive.

@brandones my question was did you modify the HTML to make it Boostrap compliant for headers or did you only change styling to make it responsive only

**Pull request merged**
