### PR TITLE
GSoC 2019: Patient Search Criteria Module

### PR DESCRIPTION
**Pull request by Reyano132**
https://wiki.openmrs.org/display/projects/Patient+Search+Criteria

New patient search criteria added in the ''find Patient" widget.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@Reyano132  am testing out this module

**Comment by Reyano132** [comment]
If you face any difficulty at time of building of the module, just change the version of the node from 6.10.0 to 6.17.0

**Comment by dkayiwa** [comment]
@Reyano132 are you aware of these merge conflicts?

**Comment by Reyano132** [comment]
sir, I'm working on this PR. At the end of this week, PR will be ready for merge

**Comment by mozzy11** [comment]
@Reyano132  have you seen the merge conflicts ??

**Comment by mozzy11** [comment]
@Reyano132  can you squash your commits into one as advised here https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Reyano132** [comment]
@mozzy11 , I squashed the commits, still, the problem with Travic CI remains. Also, due to squash, all the other files which I did not change become part of the PR.

**Comment by mozzy11** [comment]
hi @Reyano132 ,  now to clean up this,
, can your can you clone a fresh copy of the core apps, and first make sure you pull the latest chages from upstream. Then Youll make a new PR , with this solution https://stackoverflow.com/questions/55674746/travis-sh-0-cant-open-etc-init-d-xvfb

**Comment by Reyano132** [comment]
Here is my new PR : https://github.com/openmrs/openmrs-module-coreapps/pull/219

**Pull request closed without merging**
