### PR TITLE
RA-1727: Fix Obsgraph to show chart of correct concept to obs values.

### PR DESCRIPTION
**Pull request by rrameshbtech**
- Add null data point when a concept does not have observations

### CODE REVIEW

**Comment by rrameshbtech** [comment]
@mks-d , @mogoodrich, @Ruhanga Please review.

**Comment by rrameshbtech** [comment]
> Thanks @rrameshbtech. LGTM. Please also attache the ticket link to your first comment and add the ticket id the commit message.

Done.

**Comment by cioan** [comment]
Looks good @rrameshbtech . Thanks!

**Comment by Ruhanga** [comment]
@mogoodrich, @cioan, I'm merging this. Do let us know in the case of any inconsistency your side. Thanks

**Pull request merged**
