### PR TITLE
RA-1998: Core Apps Program Status widget should strip time zone compo…

### PR DESCRIPTION
**Pull request by mogoodrich**
…nent when setting date enrolled and date completed

### CODE REVIEW

**Comment by mogoodrich** [comment]
I've done some testing, but admittedly it's hard to test fully until I get it up on a staging server and can mimic having a client and a server in separate time zone.  (Or, yes, @mseaton  I guess I could have used docker... :) )

**Comment by mogoodrich** [comment]
After discussion with @mseaton  will likely make a few changes, closing this for now.

**Comment by dkayiwa** [comment]
> closing this for now.

@mogoodrich does this mean you are going to close this pull request?

**Comment by mogoodrich** [comment]
Yes, @dkayiwa , thought I had, will do so know, hopefully reopening later in the day/week... :)

**Pull request closed without merging**
