### PR TITLE
RA-981 Add VisitType to VisitContextModel class

### PR DESCRIPTION
**Pull request by gayanW**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rbuisson what do you think of this pull request?

**Comment by rbuisson** [comment]
Sorry for replying late.
Looking at the code, this seems right to me. However, I am not currently able to try it on a local dev server.

@dkayiwa, looks like there is no unit tests for this class. Should they be provided too?

**Comment by dkayiwa** [comment]
@gayanW did you take a look at the talk post link for Darius's recommendation regarding how this should be?

**Comment by gayanW** [comment]
Yeah I did refer that thread. He wants visitType to be of type SimpleObject. I've followed the way used within the coreapps module to construct the [SimpleObject](https://github.com/openmrs/openmrs-module-uiframework/blob/master/api/src/main/java/org/openmrs/ui/framework/SimpleObject.java#L35).

Let me know if the approach is correct. I'll try write a test case in the weekend.

**Comment by dkayiwa** [comment]
@gayanW did you see a line of his which looks like this? this.visitType = ConversionUtil.convertToRepresentation(visit.getVisit().getVisitType(), Representation.DEFAULT); // these are from the webservices.rest module

**Comment by dkayiwa** [comment]
@gayanW are you still working on this?

**Comment by gayanW** [comment]
Yup. To my understanding the approach I had used must be correct. I posted here: https://talk.openmrs.org/t/how-to-conditionally-display-forms/4197/21?u=gayanw f for further clarification. But yet to receive a reply.

**Comment by dkayiwa** [comment]
@gayanW can you respond to the original thread and tell darius why his suggested approach does not work? Remember to mention his name.

**Comment by gayanW** [comment]
@dkayiwa I'm sorry that this took so long. 

For some reason adding dependencies of webservices.rest module causes test cases to be failed.
https://talk.openmrs.org/t/how-to-conditionally-display-forms/4197/20?u=gayanw

If this issue is urgent, let me know. I'll unassigned myself from the issue. Thanks.

**Comment by dkayiwa** [comment]
@gayanW hopefully you are not good to finish this off. 😊

**Comment by dkayiwa** [comment]
Closing this because the author opened https://github.com/openmrs/openmrs-module-coreapps/pull/95

**Pull request closed without merging**
