### PR TITLE
"Add LastVisit" and "Edit Visit" require an "End Date"

### PR DESCRIPTION
**Pull request by sherrif10**
This code will record current date of the edit visit as the first commit
https://issues.openmrs.org/projects/RA/issues/RA-950?filter=allopenissues
Kindly review this PR and advise me on key notes @dkayiwa  thanks

### CODE REVIEW

**Comment by mozzy11** [comment]
No w sharif there are alot of issues with this PR .
* Squash your commits into one
* Make sure you make a PR from a branch whose name  corresponds to the ticket id  ,not form the master
* Always make sure your master branch is uptodate wih the latest changes from the Upstream
*

**Comment by sherrif10** [comment]
Thanks alot@mozzy

**Comment by dkayiwa** [comment]
Did you see the travis build failure?

**Comment by sherrif10** [comment]
yes travis failed due to mis leading of branch trees and outdated master
branch. i got it thanks

**Comment by sherrif10** [comment]
Hello , @mozzy11 ,  advise  me of how to close this pull request and re work on it again thanks

**Comment by sherrif10** [comment]
Old days commits

**Pull request closed without merging**
