### PR TITLE
RA-1244: Code reformatting.

### PR DESCRIPTION
**Pull request by mks-d**
Same as 8cc5b59 (but without touching .travis.yml), this is reformatting ahead of the actual change implementing RA-1244.

### CODE REVIEW

**Comment by mks-d** [comment]
@dkayiwa, could you process that one so that I can submit the _actual_ PR?
This is to ensure that 1.7.x and master don't diverge. See 962b4f2.

**Comment by dkayiwa** [comment]
@mks-d is this for only formatting? I see some new constants.

**Comment by mks-d** [comment]
It should be only reformatting/re-indenting, which new constants did you spot?

**Comment by dkayiwa** [comment]
ENCOUNTER_TEMPLATE_EXTENSION and GP_RECENT_DIAGNOSIS_PERIOD_IN_DAYS

**Comment by mks-d** [comment]
Are they not already here: https://github.com/openmrs/openmrs-module-coreapps/blob/master/api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java#L27-L29
?

**Comment by dkayiwa** [comment]
Oh i see!

**Pull request merged**
