### PR TITLE
RA-1853 : Change the strong label on widget latestobsforconceptlist

### PR DESCRIPTION
**Pull request by JFigueiredo89**
Change the strong label and create the class inlineSpan and give it some proprieties in the scss.

## Issue I worked on 

 see: https://issues.openmrs.org/browse/RA-1853

### CODE REVIEW

**Comment by HerbertYiga** [comment]
thanks @JFigueiredo89   which exact attachment is showing the new label on your ticket Id?

**Comment by JFigueiredo89** [comment]
I don´t create a new label, I only changed a html tag, that was in ´strong´ and now it´s a ´span´.

**Comment by dkayiwa** [comment]
Thank you so much @JFigueiredo89 for working on this! 👍 
Did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by HerbertYiga** [comment]
> @HerbertYiga, I don´t create a new label, I only changed a html tag, that was in ´strong´ and now it´s a ´span´.

@JFigueiredo89 ok then,you can add the ticket Id to your commit as per the instructions on the link that @dkayiwa shared

**Pull request closed without merging**
