### PR TITLE
RA-1719: Program, Program Status and Relationship widgets not properl…

### PR DESCRIPTION
**Pull request by mogoodrich**
…y retrieving session use

### CODE REVIEW

**Comment by rrameshbtech** [comment]
@mogoodrich The new change in the session url (removing custom) has effects in the response returned by the server. 

For example `https://demo.openmrs.com/openmrs/ws/rest/v1/session` returns below which does not have name for privileges (older one had). which is what checked in all the functions to validate whether the logged user has particular privilege or not.

```
 "privileges": [
            {
                "uuid": "d05118c6-2490-4d78-a41a-390e3596a237",
                "display": "Get Concept Datatypes",
                "links": [
                    {
                        "rel": "self",
                        "uri": "http://uat.openmrs-icrc.com/openmrs/ws/rest/v1/privilege/d05118c6-2490-4d78-a41a-390e3596a237"
                    }
                ]
            },
            {
                "uuid": "d05118c6-2490-4d78-a41a-390e3596a238",
                "display": "Get Concept Classes",
                "links": [
                    {
                        "rel": "self",
                        "uri": "http://uat.openmrs-icrc.com/openmrs/ws/rest/v1/privilege/d05118c6-2490-4d78-a41a-390e3596a238"
                    }
                ]
            },
```

Could you help us to fix this?

**Comment by Ruhanga** [comment]
Thanks for this observation @rrameshbtech. This in a way is fixed by depending on version 2.28.0 and above of `webservices.rest` module.

cc: @mogoodrich.

**Comment by mogoodrich** [comment]
Yes, sorry @rrameshbtech  and @Ruhanga ... this bug fix was across both REST web services and Core Apps and so Core Apps needs the late REST module... I did a release of REST, but neglected to update the dependency in Core Apps, my apologies... I just did that now...

**Comment by mogoodrich** [comment]
Of course it looks like the build failed after my change... I'm in a meeting now but will check when I'm out.

**Comment by mogoodrich** [comment]
For the record, I had issues updating the Core Apps module to use the latest REST, but I did release the REST module and the ref app now relies on that version.

**Pull request merged**
