### PR TITLE
adding config files for RA-1341

### PR DESCRIPTION
**Pull request by varshateratipally**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@varshateratipally did you see the travis build failure?

**Comment by dkayiwa** [comment]
@cioan do you think this is good to merge?

**Comment by cioan** [comment]
Hi @varshateratipally and @dkayiwa , the patientPage parameter value is incorrect. And we do not need to specifically define it here. By default the patient page is the clinician facing dashboard.

**Comment by varshateratipally** [comment]
Hello,

Could you please suggest what can be done?

Thanks,
Varsha

**Comment by cioan** [comment]
Hi @varshateratipally , here is the default config for the relationships widget:
```
config: {
    "widget": "relationships",
    "baseAppPath", "/coreapps",
    "editPrivilege", CoreAppsConstants.PRIVILEGE_EDIT_RELATIONSHIPS,
    "patientPage", "/coreapps/clinicianfacing/patient.page?patientId={{patientUuid}}",
    "icon": "icon-group",
    "label": "Family",
    "maxRecords": "3"
}
```

**Comment by dkayiwa** [comment]
@varshateratipally are you still working on this?

**Comment by dkayiwa** [comment]
@varshateratipally ping 😊

**Comment by dkayiwa** [comment]
@varshateratipally ping me to reopen this pull request when you resume working on it. 😊

**Pull request closed without merging**
