### PR TITLE
RA-1485

### PR DESCRIPTION
**Pull request by slubwama**
Restricting viewing of Encounter data basing on the encounter type privilege
https://issues.openmrs.org/browse/RA-1485

### CODE REVIEW

**Comment by dkayiwa** [comment]
@slubwama can you squash these commits into one?

**Comment by slubwama** [comment]
@dkayiwa I think I have squashed.

**Comment by dkayiwa** [comment]
@slubwama are you just guessing? 😊 
You can just look at this pull request to see if it now has one commit or not.

**Comment by slubwama** [comment]
@dkayiwa  maybe guide me on how fully squashed commits may be. I followed guidance from this link to make this happen https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by dkayiwa** [comment]
There are more than one option for doing so, on that page. Did you look at the others?

**Comment by slubwama** [comment]
@dkayiwa  this is the only way how you squash commits into on.

**Comment by dkayiwa** [comment]
@slubwama this pull request has too make commits. Would it be easier for you to just create a new one?

**Comment by slubwama** [comment]
@dkayiwa  I think so too. tried to squash it over 4 times and its not seeming to accept

**Comment by dkayiwa** [comment]
Surely, it was such a stubborn one. 😊

**Pull request closed without merging**
