### PR TITLE
RA-1592: Minor styling fixes + dependency on UICM 2.9.0-SNAPSHOT.

### PR DESCRIPTION
**Pull request by Akayeshmantha**
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now

1 Data management page css fix.
2 Sys admin page css fix.
This PR will have more commit's when the project is going forward.

Ticket ID :- https://issues.openmrs.org/browse/RA-1592

### CODE REVIEW

**Comment by mozzy11** [comment]
@Akayeshmantha  , if possible it will be better if you could attach a screenshot before and after , for easy rebiewn . Otherwise good Job

**Comment by mozzy11** [comment]
cc @mks-d

**Comment by Akayeshmantha** [comment]
Before 
https://drive.google.com/file/d/1Ui0UqVt06X8VBedDfXjOiHkLQnrXQvM1/view?usp=sharing
https://drive.google.com/file/d/1QJaixIRI8rKy5lb8n-D-hnG5s9R3ltX9/view?usp=sharing
After :-

https://drive.google.com/file/d/1DLOmfKRGgOsgigOsFTwVvKCo5IoOcwwm/view

**Comment by mozzy11** [comment]
great work @Akayeshmantha

**Comment by Akayeshmantha** [comment]
@mks-d It's addressing this issue.

https://talk.openmrs.org/t/core-apps-patient-page-look-and-feel-different-on-desktop-browsers/24578/108?u=ayesh

**Comment by mks-d** [comment]
@Akayeshmantha or @mozzy11 could you please set a PR headline message that actually describes the change that is being brought in?

**Comment by Akayeshmantha** [comment]
Hi @mks-d  yes will do there will be more changes coming will do afterwords.

**Comment by mozzy11** [comment]
thanks @mks-d for the merge

**Pull request merged**
