### PR TITLE
RA-1699: 'obsacrossencounters' widget table to be horizontally auto-scrollable.

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket : https://issues.openmrs.org/browse/RA-1699

### CODE REVIEW

**Comment by cioan** [comment]
Hi @Ruhanga and @mks-d , I just issued a PR to replace the html table with bootstrap grid:
https://github.com/openmrs/openmrs-module-coreapps/pull/290
Do you think it would be possible to implement auto-scrollable with the bootstrap div? Thanks.

**Comment by mogoodrich** [comment]
Thanks @mks-d ... @Ruhanga  feel free to just revert #290 if that would be easier... once we see how it looks like with the scrollbar we can better assess/debate if we want re-add the bootstrap grid implementation.

**Comment by Ruhanga** [comment]
Thanks @mogoodrich, @mks-d. I have simply resolved the merge conflicts by undoing the previous changes. This is good to merge.

**Comment by mogoodrich** [comment]
Thanks @Ruhanga I will go ahead and merge so we can check this out on our staging servers.

**Pull request merged**
