### PR TITLE
RA-1640: Localizing link titles in custom links widget.

### PR DESCRIPTION
**Pull request by sukreet**
Translating link titles in custom links widget.
[Link to card](https://issues.openmrs.org/browse/RA-1640)

### CODE REVIEW

**Comment by HerbertYiga** [comment]
add ticket description and ticket Id as recommended here https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by sukreet** [comment]
Translating link titles in custom links widget.
[Link to card](https://issues.openmrs.org/browse/RA-1640)

**Comment by mogoodrich** [comment]
Merged, thanks @sukreet!

What is your OpenMRS ID so I can update the ticket.

**Comment by sukreet** [comment]
@mogoodrich Thanks,
My openmrs id is `sukreet` .

**Comment by mks-d** [comment]
Thanks @mogoodrich!

**Pull request merged**
