### PR TITLE
RA-1316 Missing css on Active Visit page

### PR DESCRIPTION
**Pull request by andrewmoko**

### CODE REVIEW

**Comment by andrewmoko** [comment]
https://issues.openmrs.org/browse/RA-1316

**Comment by dkayiwa** [comment]
Which pages use this css?

**Comment by andrewmoko** [comment]
@dkayiwa It's only the active visit page (/openmrs/coreapps/activeVisits.page). 

When working on RA-977, I included the css under webapp/resources/styles instead of compass/sass hence the file is non-existent.

**Comment by dkayiwa** [comment]
Oh i see! Thanks for the clatification. 😊

**Pull request merged**
