### PR TITLE
RA-1465: Move ConditionListUI to coreapps

### PR DESCRIPTION
**Pull request by andrewmoko**

### CODE REVIEW

**Comment by andrewmoko** [comment]
cc:@mogoodrich

**Comment by mogoodrich** [comment]
@andrewmoko sorry, I have been on vacation, I will plan to look at this sometime this week...

**Comment by mogoodrich** [comment]
Lots lot style issues found by the Codacy/PR reviewer... however, I don't know how relevant these are... I will merge this in and test shortly.

**Comment by mogoodrich** [comment]
@andrewmoko  now that it is merged in, it would be worth having a discussion about whether we should just move the restangular dependency to uicommons (or elsewhere) so that other widgets could use it... and also if there is any other generic functionality that we "pull up" to a higher level?  Or perhaps it's better to keep it standalone and self-contains for now... I'd be interested in others opinions.

**Comment by andrewmoko** [comment]
@mogoodrich I'm in total agreement. Restangular should definitely be moved to uicommons.

**Comment by mogoodrich** [comment]
Great, feel free to go ahead and move it and issue a pull request if you feel inspired... :)

I'm just doing some testing and it looks like the css isn't being picked up on the Add Conditions page... I'm seeing two errors on that page in the console logs... one that conditions.css can't be found, and the other that conditions.history.model.js can't be found.

Also, we should change the page controller names so that each word is capitalized, ie:

AddconditionPageController -> AddConditionPageController
ManageconditionsPageController -> ManageConditionsPageController

Would you be able to make these changes?

Thanks so much for doing all this!

**Comment by andrewmoko** [comment]
Sure!

**Comment by mogoodrich** [comment]
Also, fyi just made this tweak to the includes here because I was seeing some bugs... testing now:

https://github.com/openmrs/openmrs-module-coreapps/commit/5ae4b7d8eae49632b15e31ba1aee8e3080900b1c

**Comment by andrewmoko** [comment]
https://github.com/openmrs/openmrs-module-coreapps/pull/135

**Pull request merged**
