### PR TITLE
RA-1820 Unused local variables should be removed

### PR DESCRIPTION
**Pull request by achilep**
Issue I work on : https://issues.openmrs.org/browse/RA-1820

### CODE REVIEW

**Review by sacull — APPROVED** [review]
It looks good to me. ;)
@mogoodrich @dkayiwa

**Comment by dkayiwa** [comment]
@achilep you seem to be above the level of these intro tickets.

**Comment by achilep** [comment]
sorry @dkayiwa @sacull I didn't know that these ticket was intro ticket .

**Comment by achilep** [comment]
@dkayiwa  @sacull should I close these Pull Request ?
thanks

**Comment by dkayiwa** [comment]
@achilep when the change to make is such simple that it does not help you learn, then ... 😊 

No need to close them.

**Comment by achilep** [comment]
> @achilep when the change to make is such obviously simple that it does not help you learn, then ... 
> 
> No need to close them.

that is true , thanks @dkayiwa

**Comment by dkayiwa** [comment]
@achilep this one though simple, is a community priority. Do you mind it? https://issues.openmrs.org/browse/RA-1620

**Comment by dkayiwa** [comment]
@achilep here goes another good community priority of medium complexity: https://issues.openmrs.org/browse/RA-552 😊

**Comment by dkayiwa** [comment]
@sacull https://issues.openmrs.org/browse/RA-552 serves you well too. 😊

**Comment by achilep** [comment]
thanks @dkayiwa

**Comment by sacull** [comment]
@dkayiwa I will not promise anything, because recently I lack time for everything, but I will try to reflect on this problem as soon as I find a longer moment.

**Pull request merged**
