### PR TITLE
RA-1306 Visits By Encounter Type Widget

### PR DESCRIPTION
**Pull request by AdamGrzybkowski**
I wasn't sure what to do if there were no encounterTypes for a visit. See below for my solution. Second thing is that for now clicking the visit date redirects you only to all patient visits not specific one. To make this we need to provide visit and patient id which cannot be done via REST (?) so we would have to modify fragment controller ?

Screen shot
ra-1306

### CODE REVIEW

**Comment by ssmusoke** [comment]
@AdamGrzybkowski I think its okay to leave the encounter types blank if there are none for a visit. 

Can't the visitId and patientId be gotten from the visit via REST? Since I see visit.encounterType I am assuming that you can have visit.patientId and visit.id (please excuse my ignorance of REST here)

**Comment by rkorytkowski** [comment]
@ssmusoke, REST doesn't expose IDs, just UUIDs. @AdamGrzybkowski, we need to make the page you link under dates to accept UUIDs in addition to IDs.

**Comment by ssmusoke** [comment]
@rkorytkowski Got you - my understanding has been that the patientId takes both an Id and uuid in the same parameter throughout so I assumed that it was the same for visit

**Comment by rkorytkowski** [comment]
@AdamGrzybkowski , did you actually verify it doesn't work when you pass uuid instead of id as Stephen suggests? :)

**Comment by rkorytkowski** [comment]
http://qa-refapp.openmrs.org/openmrs//coreapps/patientdashboard/patientDashboard.page?patientId=3282d83b-55c3-44b5-af39-40f599159076&visitId=6795#

**Comment by AdamGrzybkowski** [comment]
@rkorytkowski Yes I verified it but I see you already did it too : )

**Comment by rkorytkowski** [comment]
The fix should be easy. Look around here https://github.com/openmrs/openmrs-module-coreapps/blob/master/omod/src/main/java/org/openmrs/module/coreapps/page/controller/patientdashboard/PatientDashboardPageController.java#L43

**Pull request merged**
