### PR TITLE
RA-1792: Overhaul of Condition UI

### PR DESCRIPTION
**Pull request by ibacher**
This is a draft PR of an overhaul of the condition UI designed to work in concert with the PR for [TRUNK-5888](https://github.com/openmrs/openmrs-core/pull/3632), although I'm not certain that is required.

Main highlights:

* Dates are no longer required
* Setting conditions active or inactive actually works
* Simplified the implementation from 3 pages to 2 pages
* Removed broken delete functionality from the Dashboard widget
* Removed dependency on Restangular

### CODE REVIEW

**Comment by ibacher** [comment]
@mogoodrich @mseaton FYI. This piece is not yet complete, but I did want to provide a detailed update.

**Comment by mogoodrich** [comment]
Awesome @ibacher , thanks so much for the update!  Let me know when it's ready for review... though, honestly, considering how big the changes are and my unfamiliarity with the existing code, I'll probably just give a quick once-over, but instead will really look to test the widget post-merge...

**Comment by mogoodrich** [comment]
@ibacher is this ready for a full review?

**Comment by ibacher** [comment]
@mogoodrich Yes, barring the conflicts on the `messages.properties` files. One thing I wasn't quite able to sort: the field used for the condition is a `<coded-or-freetext>` field because I couldn't find a pure `Coded` field, so it works for coded conditions, but not for non-coded conditions. Ellen had mentioned that free text conditions weren't really something that needed to be supported, so I kind of ignored it, but is there an elegant way to make the `<coded-or-freetext>` field coded only?

**Comment by mogoodrich** [comment]
Cool... not sure @ibacher  but I'll try to take a look this week.

The core changes in the other PR are required as well for things to work, I assume?

**Comment by ibacher** [comment]
Yes, this pretty much requires the changes to core.

**Comment by mogoodrich** [comment]
Just as an update @ibacher  in the Core thread did you end up saying that this may *not* require the changes to Core?

**Comment by ibacher** [comment]
@mogoodrich Sorry... I thought I replied to that comment ages ago. So, technically this is still using the same API as the before, the API in emrapi. Because of that, the changes in this PR and the PR for TRUNK-5888 are independent of one another but because this overhaul actually creates a simpler and more maintainable codebase for the condition UI, I'd probably want them applied together.

**Comment by mseaton** [comment]
@ibacher - I just merged master up into this branch.  I may have lost some of the message properties changes in the non-english files.  Are these not managed by transifex though?

**Comment by ibacher** [comment]
They should be managed through Transifex. IIRC (and it's been a minute) the changes to non-English translations were just adding commented out properties for the new keys I added in this PR, so it shouldn't matter.

**Pull request merged**
