### PR TITLE
Make ctrl-click on a patient program link open in a new tab

### PR DESCRIPTION
**Pull request by brandones**
https://issues.openmrs.org/browse/RA-1530

### CODE REVIEW

**Review by mogoodrich — COMMENTED** [review]
LGTM, but can we create a ticket in OpenMRS Jira (in the RA project) and associate the commit with that for better tracking? Thanks!

**Comment by brandones** [comment]
Oh yeah, just forgot to link it. Fixed. Thanks Mark!

**Comment by mogoodrich** [comment]
Cool, in the future can you include the ticket in the commit message as well?

**Comment by brandones** [comment]
Oh yeah, definitely. Thanks!

**Pull request merged**
