### PR TITLE
RA-1830: Conditionally executed code should be reachable

### PR DESCRIPTION
**Pull request by DBryzz**
[RA-1830](https://issues.openmrs.org/browse/RA-1830): Conditionally executed code should be reachable

Removed unreachable if statement. [Issue Description](https://issues.openmrs.org/browse/RA-1830)

I am opened for corrections

### CODE REVIEW

**Review by sacull — APPROVED** [review]
It looks good to me.

**Comment by sacull** [comment]
@DBryzz I see that you are already familiar with JIRA and GitHub. Perhaps it's time to leave the introductory tickets alone and do something more difficult? ;)

**Comment by DBryzz** [comment]
Thanks, @sacull for your follow up so far 
I've heard you and as you suggested I will leave the other introductory tickets.
If you don't mind pointing me to the next level of difficulty on JIRA, it will help a lot.

**Comment by sacull** [comment]
I will not try to show you the next ticket, because it all depends on how you feel about it yourself. Nevertheless, I will try to show you the direction. First, look at tickets labeled "community-priority". If you do not find something that you will be able to undertake, look for tickets with the status "Ready for work" or "Waiting for Dev" with the filter "Assignee" with the value "Unassigned".

**Pull request merged**
