### PR TITLE
RA-1609:Add condition UI enhancement

### PR DESCRIPTION
**Pull request by haripriya999**
# RA-1609:Add condition UI enhancement

## Description of what I changed
Changed UI for add conditions

## Issue I worked on

see https://issues.openmrs.org/browse/RA-1609

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by HerbertYiga** [comment]
Did this pass locally?

**Comment by dkayiwa** [comment]
@haripriya999 of the screenshots on the ticket, which one shows the state of things before your changes?

**Comment by haripriya999** [comment]
@dkayiwa I'm sorry I missed to upload the before screenshots. I updated the attachments :)

**Comment by dkayiwa** [comment]
Why do you want end date on the right hand side instead of below as it was?

**Comment by haripriya999** [comment]
> Why do you want end date on the right hand side instead of below as it was?

While toggling the status, it is creating a lot of white space below the onset date when a condition is active, which isn't giving a good look.

**Comment by dkayiwa** [comment]
@haripriya999 did that come from the produce owner? Or did you discuss it with them?

**Comment by haripriya999** [comment]
> @haripriya999 did that come from the product owner? Or did you discuss it with them?

I'm sorry for delay in reply. I missed your comment on this PR. I didn't understand what you meant? who is the product owner?

**Comment by haripriya999** [comment]
@dkayiwa Could you please take a look at this. I fixed the merge conflicts. Thank you.

**Comment by dkayiwa** [comment]
Was this a request from @lnball or any one else? Or did you discuss it with them?

**Comment by haripriya999** [comment]
@dkayiwa  I discussed this on talk: https://talk.openmrs.org/t/congrats-for-gsoc/23120/85 , Also @lnball approved these changes.

**Pull request merged**
