### PR TITLE
RA-1832: .size() method replace by .isEmpty() method to check collect…

### PR DESCRIPTION
**Pull request by utkarsh-3112**
**issue:**
[RA-1832](https://issues.openmrs.org/browse/RA-1832)

**Description of what I change**
- I replace the .size() method  by .isEmpty() method to check collection is empty or not

### CODE REVIEW

**Comment by dkayiwa** [comment]
The ticket link does not look correct.

**Comment by utkarsh-3112** [comment]
Sorry for the mistake. I have corrected the link

**Comment by dkayiwa** [comment]
Did you claim the ticket as a advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
How? Did you hit the `Claim Issue` button?

**Comment by utkarsh-3112** [comment]
Yes, I hit the Claim issue button.

**Comment by utkarsh-3112** [comment]
Actually, I click the **assign to me**  in the people section. I guess I should have clicked **Claim Issue** button .

**Comment by dkayiwa** [comment]
Can you do a final round of cross checking to see if you have done all that is mentioned at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by utkarsh-3112** [comment]
Okay, I will check

**Comment by utkarsh-3112** [comment]
> Can you do a final round of cross checking to see if you have done all that is mentioned? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

I cross-checked all points which are mentioned. I guess it looks fine.

**Comment by dkayiwa** [comment]
@utkarsh-3112 your pull request does not seem to deal with all the places mentioned in the ticket description.

**Comment by utkarsh-3112** [comment]
The place which points in this link https://github.com/openmrs/openmrs-module-coreapps/blob/1.29.0/omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java#L93 
is not present in the file https://github.com/openmrs/openmrs-module-coreapps/blob/master/omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java

**Pull request merged**
