### PR TITLE
RA-1619: Display forms for patients based on the program(s) enrolled

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/RA-1619
Added functionality for a situation where a patient is enrolled on a particular program, and only forms that relate to the program should be displayed.

### CODE REVIEW

**Comment by ODORA0** [comment]
@dkayiwa could you please review this code? Trying to look through the error log but can't find much.

**Comment by HerbertYiga** [comment]
did you get this pass locally??

**Comment by dkayiwa** [comment]
Sorry @ODORA0 for not telling you. This ticket and RA-1620 are reserved for some group of developers that am training here. Feel free to pick any others.

**Comment by ODORA0** [comment]
Ooh! Definately cool with me @dkayiwa

**Pull request closed without merging**
