### PR TITLE
RA-1620 Ensure that form filling follows the correct order

### PR DESCRIPTION
**Pull request by achilep**
issue I work on : https://issues.openmrs.org/browse/RA-1620

### CODE REVIEW

**Comment by achilep** [comment]
hello @sacull  please I need your opinion on this PR . thanks

**Comment by sacull** [comment]
@achilep Please note that this is a submission from August 2019. Then line 96 was in a different code place. This is the version of the file from that period: https://github.com/openmrs/openmrs-module-coreapps/blob/1.23.0/omod/src/main/java/org/openmrs/module/coreapps/page/controller/clinicianfacing/PatientPageController.java#L96

**Comment by achilep** [comment]
cc @sacull

**Comment by sacull** [comment]
Can this change be tested in some way?

**Pull request merged**
