### PR TITLE
RA-1826 Modifiers should be declared in the correct order

### PR DESCRIPTION
**Pull request by achilep**
Issue I work on : https://issues.openmrs.org/browse/RA-1826

### CODE REVIEW

**Comment by sacull** [comment]
@achilep When the PR is ready be sure to click the "Ready for Testing" button.

**Review by sacull — APPROVED** [review]
@achilep I think there are enough introductory tickets, time for something more difficult. ;)
@mogoodrich @dkayiwa It looks good to me.

**Comment by achilep** [comment]
@sacull  I am at this level : https://github.com/openmrs/openmrs-module-coreapps/pull/351

**Comment by achilep** [comment]
> @achilep I think there are enough introductory tickets, time for something more difficult. ;)
> @mogoodrich @dkayiwa It looks good to me.


I had already done the PR before realizing that this is an intro ticket.

**Comment by sacull** [comment]
@achilep If that is your decision, Mr /dev/2. ;)

Please remember to clean up also on JIRA.

**Comment by achilep** [comment]
> If that is your decision, Mr /dev/2. ;)
thanks @sacull  :)
I may not have enough privilege to unassigned the ticket

**Comment by achilep** [comment]
> Mr /dev/2
Ahahah, Mr /dev/5 hidden

**Comment by sacull** [comment]
> I may not have enough privilege to unassigned the ticket

I see two solutions in this case:
1. you can open closed PR and we are proceeding to merge them, there are a lot of introductory tickets, so if these few run out, nobody will notice ;)
2. you can make a list with links to these tickets and send to someone who can change their status: Ian, Burke, Mike or Daniel.

Whatever choice you make, you can count on my support.

**Comment by achilep** [comment]
i choice solution 1 . Thanks @sacull

**Comment by sacull** [comment]
I am currently preparing the introductory tickets for the next module, so feel free to do the ones you have already started doing. ;)

**Pull request merged**
